# Use Node base image
FROM node:22

# Set working directory
WORKDIR /app

# Copy files
COPY . .

# Install deps and build
RUN npm install
RUN npm run build

# Expose default port (Next.js)
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
